// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8aZlORnNAMdxP7xS_n_v6RR2oqHL-20',
    appId: '1:616833281378:web:7ed5819a94a430d92f503b',
    messagingSenderId: '616833281378',
    projectId: 'gestao-familiar-app',
    authDomain: 'gestao-familiar-app.firebaseapp.com',
    storageBucket: 'gestao-familiar-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqB07eedt2OzkKQsU1DoR9tMRnPqGMz80',
    appId: '1:616833281378:android:0b050528d841b5bc2f503b',
    messagingSenderId: '616833281378',
    projectId: 'gestao-familiar-app',
    storageBucket: 'gestao-familiar-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIMkUrEd5I42BXHdltbF-HNg7dl0CelLQ',
    appId: '1:616833281378:ios:5b1ea84e2d5899c22f503b',
    messagingSenderId: '616833281378',
    projectId: 'gestao-familiar-app',
    storageBucket: 'gestao-familiar-app.firebasestorage.app',
    iosBundleId: 'com.example.gestaoFamiliarApp',
  );
}
